FROM python:3.10-slim

WORKDIR /app

# Копируем зависимости
COPY bot/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY bot/bot.py .
COPY bot/run.sh .

CMD ["python", "bot.py"]
