# Используем официальный Python образ
FROM python:3.11-slim

# Устанавливаем зависимости для psycopg2 и другие системные библиотеки
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы requirements.txt и устанавливаем зависимости
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь исходный код приложения
COPY . .

# Команда запуска uvicorn (по умолчанию)
CMD ["uvicorn", "parser_api:app", "--host", "0.0.0.0", "--port", "8050"]
